version: 0.2

phases:
  install:
    commands:
      - npm install typescript
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'